language: python
python:
    - "2.7"

install:
    - sudo apt-get build-dep --ignore-missing -y python-scipy
    - pip install -r requirements_1.txt
    # tables has some dependencies which must be installed first:
    - pip install -r requirements_2.txt
    - wget -O models/en-default.pyrnn.gz http://www.tmbdev.net/en-default.pyrnn.gz
    - python setup.py install

script: ./run-test
